name: six-ios v6

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest


    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Manually install FVM and add it to PATH
      - name: Install FVM
        run: |
          flutter pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Verify FVM installation
        run: fvm --version

      - name: Build common lib
        run: |
          git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com/".insteadOf "git@github.com:"
          make sixcommon

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Replace with the Go version you need
 
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7
          bundler-cache: true

      - name: Install bundler
        run: gem install bundler:2.4.22

      - name: Install fastlane
        run: bundler install

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
          p12-password: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}
          keychain-password: signingtmp

      - name: Make default keychain
        run: security default-keychain -s ~/Library/Keychains/signing_temp.keychain-db

      - name: Build iOS binary
        run: bundle exec fastlane build_v6 --verbose
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
          KEYCHAIN_PATH: ~/Library/Keychains/signing_temp.keychain-db
